networks:
  $NAME$_network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.14.0.0/24
  # =====================================
volumes:
  postgres_$NAME$_data:
  redis_$NAME$_data:
  # =====================================
services:
  $NAME$: &$NAME$
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: $NAME$_app
    container_name: $NAME$_dev
    networks:
      $NAME$_network:
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.env
    ports:
      - 8080:8080
    command: just build manage-start-logfile open-devlog
  # =====================================
  postgres:
    image: postgres:latest
    container_name: postgres_$NAME$_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    networks:
      $NAME$_network:
    volumes:
      - postgres_$NAME$_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # =====================================
  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: mailpit_$NAME$_dev
    networks:
      $NAME$_network:
    ports:
      - 8025:8025
      - 1025:1025
  # =====================================
  redis:
    image: redis:latest
    container_name: redis_$NAME$_dev
    networks:
      $NAME$_network:
    volumes:
      - redis_$NAME$_data:/data
    ports:
      - 6379:6379
  # =====================================
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_$NAME$_dev
    networks:
      $NAME$_network:
    depends_on:
      - redis
    ports:
      - 5540:5540
  # =====================================
  celeryworker:
    <<: *$NAME$
    image: celeryworker_$NAME$_dev
    container_name: celeryworker_$NAME$_dev
    depends_on:
      - redis
      - postgres
      - mailpit
      - $NAME$
    ports: []
    command: just celery-worker
  # =====================================
  celerybeat:
    <<: *$NAME$
    image: celerybeat_$NAME$_dev
    container_name: celerybeat_$NAME$_dev
    depends_on:
      - redis
      - postgres
      - mailpit
      - $NAME$
    ports: []
    command: just celery-beat
  # =====================================
  flower:
    <<: *$NAME$
    image: flower_dev
    container_name: flower_dev
    depends_on:
      - redis
      - postgres
      - mailpit
      - $NAME$
    ports:
      - 5555:5555
    command: just celery-flower
  # =====================================
  node:
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    image: frontend_$NAME$_app
    container_name: frontend_$NAME$_dev
    networks:
      $NAME$_network:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
