networks:
  $NAME$_gunicorn_network:
    driver: bridge
  # =====================================
services:
  $NAME$: &$NAME$
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: $NAME$_app
    container_name: $NAME$_gunicorn
    networks:
      $NAME$_gunicorn_network:
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.env
    command: just build start-gunicorn
    restart: always
  # =====================================
  nginx:
    image: nginx:latest
    container_name: nginx_$NAME$_gunicorn
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Cairo
    depends_on:
      - $NAME$
    networks:
      $NAME$_gunicorn_network:
    volumes:
      - ./compose/nginx/gunicorn:/etc/nginx/conf.d
      - .:/app:z
    ports:
      - 80:80
      - 443:443
    restart: always
  # =====================================
  celeryworker:
    <<: *$NAME$
    image: celeryworker_$NAME$_app
    container_name: celeryworker_$NAME$_app
    ports: []
    command: just celery-worker
    restart: always
  # =====================================
  celerybeat:
    <<: *$NAME$
    image: celerybeat_$NAME$_app
    container_name: celerybeat_$NAME$_app
    ports: []
    command: just celery-beat
    restart: always
  # =====================================
  flower:
    <<: *$NAME$
    image: flower_$NAME$_app
    container_name: flower_$NAME$_app
    command: just celery-flower
    ports:
      - 5555:5555
    restart: always
  # =====================================