services:
  docs:
    image: $NAME$_app_docs
    container_name: $NAME$_app_docs
    build:
      context: .
      dockerfile: ./compose/docs/Dockerfile
    env_file:
      - ./.envs/.env
    volumes:
      - .:/app:z
    ports:
      - '9000:9000'
    command: /start-docs
