from .auth import (
    get_data_login,  # noqa: F401
    get_data_register,  # noqa: F401
    get_invalid_username,  # noqa: F401
    remove_password2,  # noqa: F401
)  # noqa: F401
from .generate import (
    generate_data_register,  # noqa: F401
    generate_data_login,  # noqa: F401
    generate_fake_image,  # noqa: F401
    generate_data_category,  # noqa: F401
)  # noqa: F401
