# Generated by Django 5.0.4 on 2024-04-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
