name = "octo-launch"
description = "octo-launch simplifies the setup process of Django projects for faster development."
version = "v1.0"
repository = "https://github.com/caodlly/octo-launch"
author_name = "caodlly"
author_github = "https://github.com/caodlly/"
author_email = "octo.team.dev@gmail.com"
